---
disks:
  - name: usb1 # /dev/sdc
    uuid: "3aa268b0-c8f7-4d68-8a63-a04fc58b4116"
    # Disks can be non-uniform, so ensure for given disk that subdirs exist in
    # order to put certian dirs on certian disks
    # create_dirs will ve relative to /mnt point
    create_dirs:
      - media/tv
      - media/movies
      - media/anime
      - media/podcasts
      - media/pictures
      - media/music
      - media/home_videos_and_photos

  - name: hdd # /dev/sda2
    uuid: "7ccf0e05-f26f-43de-97a2-43a36445099c"
    create_dirs:
      - backups
      - jellyfin_metadata
